import { fixupPluginRules } from '@eslint/compat';
import globals from 'globals';
import importPlugin from 'eslint-plugin-import';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

const restrictedGlobals = [
  'addEventListener',
  'blur',
  'close',
  'closed',
  'confirm',
  'defaultStatus',
  'event',
  'external',
  'defaultstatus',
  'find',
  'focus',
  'frameElement',
  'frames',
  'history',
  'innerHeight',
  'innerWidth',
  'length',
  'location',
  'locationbar',
  'menubar',
  'moveBy',
  'moveTo',
  'name',
  'onblur',
  'onerror',
  'onfocus',
  'onload',
  'onresize',
  'onunload',
  'open',
  'opener',
  'opera',
  'outerHeight',
  'outerWidth',
  'pageXOffset',
  'pageYOffset',
  'parent',
  'print',
  'removeEventListener',
  'resizeBy',
  'resizeTo',
  'screen',
  'screenLeft',
  'screenTop',
  'screenX',
  'screenY',
  'scroll',
  'scrollbars',
  'scrollBy',
  'scrollTo',
  'scrollX',
  'scrollY',
  'self',
  'status',
  'statusbar',
  'stop',
  'toolbar',
  'top'
];

const forbidElements = [
  {
    element: 'select',
    message: '请使用 Picker 组件代替 <select>',
  },
];

const propWrapperFunctions = [
  'forbidExtraProps',
  'exact',
  'Object.freeze',
];

const baseRules = {
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 'warn',
  'jsx-quotes': ['error', 'prefer-single'],
  'react/sort-comp': ['warn'],
  'react/jsx-uses-react': 'off',
  'react/no-children-prop': ['error'],
  'react/no-typos': ['error'],
  'react/no-multi-comp': ['off'],
  'react/no-is-mounted': ['error'],
  'react/no-find-dom-node': ['error'],
  'react/no-direct-mutation-state': ['error'],
  'react/no-danger': ['error'],
  'react/no-unused-state': 'error',
  'react/forbid-elements': ['error', { forbid: forbidElements }],
  'react/prefer-es6-class': ['error', 'always'],
  'react/no-unescaped-entities': 'error',
  'react/require-render-return': 'error',
  'react/jsx-uses-vars': 'error',
  'react/jsx-boolean-value': ['error', 'never', { always: [] }],
  'react/jsx-closing-bracket-location': ['error', 'line-aligned'],
  'react/jsx-closing-tag-location': 'off',
  'react/jsx-curly-spacing': ['error', { when: 'never', allowMultiline: true }],
  'react/jsx-handler-names': 'off',
  'react/jsx-pascal-case': ['error', { allowAllCaps: true, ignore: [] }],
  'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
  'react/jsx-no-undef': 'error',
  'react/jsx-no-duplicate-props': ['error', { ignoreCase: true }],
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-indent-props': ['error', 2],
  'react/jsx-key': ['warn'],
  'react/jsx-no-literals': ['off', { noStrings: true }],
  'react/sort-prop-types': [
    'off',
    {
      ignoreCase: true,
      callbacksLast: false,
      requiredFirst: false,
    },
  ],
  'react/jsx-sort-prop-types': 'off',
  'react/jsx-sort-props': [
    'off',
    {
      ignoreCase: true,
      callbacksLast: false,
      shorthandFirst: false,
      shorthandLast: false,
      noSortAlphabetically: false,
      reservedFirst: true,
    },
  ],
  'react/no-deprecated': ['off'],
  'react/no-did-mount-set-state': 'off',
  'react/no-did-update-set-state': 'error',
  'react/no-will-update-set-state': 'error',
  'react/no-set-state': 'off',
  'react/no-string-refs': 'error',
  'react/prefer-stateless-function': 'off',
  'react/react-in-jsx-scope': 'off',
  'react/jsx-equals-spacing': ['error', 'never'],
  'react/no-render-return-value': 'error',
  'react/forbid-component-props': ['off'],
  'react/no-danger-with-children': 'error',
  'react/jsx-tag-spacing': ['error', { beforeSelfClosing: 'always' }],
  'react/boolean-prop-naming': 'off',
  'import/no-unresolved': 'off',
  'import/named': 'off',
  'import/default': 'off',
  'import/namespace': 'off',
  'import/export': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-deprecated': 'off',
  'import/no-extraneous-dependencies': 'off',
  'import/no-mutable-exports': 'error',
  'import/no-commonjs': [2, { allowPrimitiveModules: true }],
  'import/no-amd': 'error',
  'import/no-nodejs-modules': 'off',
  'import/first': ['error', 'absolute-first'],
  'import/imports-first': 'off',
  'import/no-duplicates': 'error',
  'import/no-namespace': 'off',
  'import/extensions': 'off',
  'import/order': [
    'off',
    {
      groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
      'newlines-between': 'never',
    },
  ],
  'import/newline-after-import': 'error',
  'import/prefer-default-export': 'off',
  'import/no-restricted-paths': 'off',
  'import/max-dependencies': ['off', { max: 10 }],
  'import/no-absolute-path': 'error',
  'import/no-dynamic-require': 'off',
  'import/no-internal-modules': ['off', { allow: [] }],
  'import/unambiguous': 'off',
  'import/no-webpack-loader-syntax': 'error',
  'import/no-unassigned-import': 'off',
  'import/no-named-default': 'error',
  'import/no-anonymous-default-export': [
    'off',
    {
      allowArray: false,
      allowArrowFunction: false,
      allowAnonymousClass: false,
      allowAnonymousFunction: false,
      allowLiteral: false,
      allowObject: false,
    },
  ],
  'import/exports-last': 'off',
  'init-declarations': 'off',
  'no-catch-shadow': 'off',
  'no-delete-var': 'error',
  'no-label-var': 'error',
  'no-restricted-globals': ['error', 'isFinite', 'isNaN', ...restrictedGlobals],
  'no-shadow': 'error',
  'no-shadow-restricted-names': 'error',
  'no-undef': 'error',
  'no-undef-init': 'error',
  'no-undefined': 'off',
  'no-unused-vars': ['error', { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
  'no-use-before-define': ['error', { functions: false, classes: false, variables: false }],
};

const typescriptRules = {
  'default-case': 'off',
  'no-dupe-class-members': 'off',
  'no-undef': 'off',
  '@typescript-eslint/consistent-type-assertions': 'warn',
  'no-array-constructor': 'off',
  '@typescript-eslint/no-array-constructor': 'warn',
  'no-use-before-define': 'off',
  '@typescript-eslint/no-use-before-define': [
    'warn',
    {
      functions: false,
      classes: false,
      variables: false,
      typedefs: false,
    },
  ],
  'no-unused-expressions': 'off',
  '@typescript-eslint/no-unused-expressions': [
    'error',
    {
      allowShortCircuit: true,
      allowTernary: true,
      allowTaggedTemplates: true,
    },
  ],
  'no-unused-vars': 'off',
  '@typescript-eslint/no-unused-vars': [
    'warn',
    {
      args: 'none',
      ignoreRestSiblings: true,
      varsIgnorePattern: '^Nerv|^React',
    },
  ],
  'no-useless-constructor': 'off',
  '@typescript-eslint/no-useless-constructor': 'warn',
  'no-shadow': 'off',
  '@typescript-eslint/no-shadow': 'error',
};

export default [
  {
    name: '@ygqygq2/eslint-config/taro-react',
    files: ['**/*.{js,mjs,cjs,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: {
      import: fixupPluginRules(importPlugin),
      react: fixupPluginRules(react),
      'react-hooks': fixupPluginRules(reactHooks),
    },
    settings: {
      react: {
        pragma: 'React',
        version: 'detect',
      },
      propWrapperFunctions,
      'import/resolver': {
        node: {
          extensions: ['.mjs', '.js', '.json', '.jsx', '.ts', '.tsx'],
        },
      },
      'import/extensions': ['.js', '.mjs', '.jsx', '.ts', '.tsx'],
      'import/core-modules': ['@tarojs/taro', '@tarojs/components'],
    },
    rules: baseRules,
  },
  {
    name: '@ygqygq2/eslint-config/taro-react-typescript',
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
        warnOnUnsupportedTypeScriptVersion: true,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: typescriptRules,
  },
];
